version: "3.3"

services:
  sdk-api:
    image: webapp-image
    environment:
      - PORT=5000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: webapp-container
    restart: always

