version: '3.3'

services:
  reverse-proxy-blue-node-api:
    image: nginx:1.19.6-alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapp-api

  webapp-api:
    image: webapp-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: webapp-container
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: