CREATE TABLE Emi (
  id SERIAL PRIMARY KEY,
  loan_amount DECIMAL(10, 2) NOT NULL,
  interest_rate DECIMAL(5, 2) NOT NULL,
  loan_tenure_months INTEGER NOT NULL,
  emi DECIMAL(10, 2) NOT NULL,
  prepayment_amount DECIMAL(10, 2) DEFAULT 0,
  remaining_balance DECIMAL(10, 2) NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
